---
title: Paginas de Errores
sidebar_label: Paginas de Errores
---

## Pagina 404 {#404-page}

La página 404 puede ser accedida con frequencia tal que Blitz provea una
página estatica 404 por defecto sin tener que añadir archivos adicionales.

### Customizando La Pagina 404 {#customizing-the-404-page}

Para crear una página 404 customizada puedes crear un archivo tal como:
`app/pages/404.js`. Este archivo sera generado estàticamente en el momento
de construcción.

```jsx
// app/pages/404.js
export default function Custom404() {
  return <h1>404 - Page Not Found</h1>
}
```

## Pagina 500 {#500-page}

Por defecto Blitz proveé una pagina de error 500 cual estilo coincide con
el estilo de la pagina 404. Esta pagina no es optimizada estaticamente por
lo que permite el reportaje de errores en el servidor. Esta es la razon
que 404 y 500 (otros errores) son separados.

### Customizando La pagina De Error {#customizing-the-error-page}

Errores 500 son manajados por ambos lado del cliente y lado del servidor
por medio del componente `Error`. Si deseas anularlo, define el archivo
`app/pages/_error.js` y añade el codigo siguiente:

```jsx
function Error({ statusCode }) {
  return (
    <p>
      {statusCode
        ? `An error ${statusCode} occurred on server`
        : "An error occurred on client"}
    </p>
  )
}

Error.getInitialProps = ({ res, err }) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}

export default Error
```

> `app/pages/_error.js` es solo utilisado en producción. En el desarollo
> ud recibiras un error con la pila de llamadas para saber donde el error
> fue originado.

## componente de límite de error personalizado {#custom-error-boundary-component}

El valor por defecto `app/pages/_app.tsx` configura un límite de error que
detecta errores que ocurren durante el procesamiento, en el lado del
cliente. Esta voluntad también detecta errores dentro de `useQuery`
o` useMutation` porque ocurren en suspenso.

En esencia, la configuración por defecto es:

```tsx
export default function App({ Component, pageProps }: AppProps) {
  return (
    <ErrorBoundary FallbackComponent={RootErrorFallback} {...etc}>
      {getLayout(<Component {...pageProps} />)}
    </ErrorBoundary>
  )
}
```

El `RootErrorFallback` es reproducido cuando ocurre un error dentro del
procesamiento (render), o una mutación o consulta suspendida. Por defecto:

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthenticationError) {
    return <LoginForm onSuccess={resetErrorBoundary} />
  } else if (error instanceof AuthorizationError) {
    return (
      <ErrorComponent
        statusCode={error.statusCode}
        title="Sorry, you are not authorized to access this"
      />
    )
  } else {
    return (
      <ErrorComponent
        statusCode={error.statusCode || 400}
        title={error.message || error.name}
      />
    )
  }
}
```

### Authentication Error Component (401) {#custom-authentication-error-component}

If your query, mutation, or render function
`throw new AuthenticationError()` when the user is not authenticated, you
can detect that within the error fallback:

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthenticationError) {
    return <MyCustomError error={error} onRetry={resetErrorBoundary} />
  }
  return (
    <ErrorComponent
      statusCode={error.statusCode || 400}
      title={error.message || error.name}
    />
  )
}
```

### Authorization Error Component (403) {#custom-authorization-error-component}

Your query, mutation, or render function may call
`throw new AuthorizationError()` when a user is authenticated but not
authorized to do something. The error fallback may handle that:

```tsx
function RootErrorFallback({
  error,
  resetErrorBoundary,
}: ErrorFallbackProps) {
  if (error instanceof AuthorizationError) {
    return <MyCustomError error={error} onRetry={resetErrorBoundary} />
  }
  return (
    <ErrorComponent
      statusCode={error.statusCode || 400}
      title={error.message || error.name}
    />
  )
}
```

## Reusing the built-in error page {#reusing-the-built-in-error-page}

You can render the built-in error page by importing `ErrorComponent`.

It accepts two props:

- `statusCode` - a number to display as the error code
- `title` - a string to display as the error message

```jsx
import { ErrorComponent } from "blitz"

export default function Page() {
  return <ErrorComponent statusCode={404} />
}
```

```jsx
import { ErrorComponent } from "blitz"

export default function Page() {
  return <ErrorComponent statusCode={401} title="Unauthorized" />
}
```
