---
title: Manejo de Errores
sidebar_label: Manejo de Errores
---

## Errores Incorporados {#built-in-errors}

Blitz viene con un número de errores útiles que puedes usar a lo largo de tu
aplicación.

- `AuthenticationError`
  - `name`: "AuthenticationError"
  - `statusCode`: 401
  - Valor predeterminado de `message`: "You must be logged in to access this"
- `CSRFTokenMismatchError`
  - `name`: "CSRFTokenMismatchError"
  - `statusCode`: 401
  - Valor predeterminado de `message`: "You must be logged in to access this"
- `AuthorizationError`
  - `name`: "AuthorizationError"
  - `statusCode`: 403
  - Valor predeterminado de `message`: "You are not authorized to access this"
- `NotFoundError`
  - `name`: "NotFoundError"
  - `statusCode`: 404
  - Valor predeterminado de `message`: "This could not be found"
- `RedirectError`
  - `name`: "RedirectError"
  - Puedes lanzar este error desde una función de renderizado si quieres
    redirigir al usuario, evitando a la vez que el usuario vea la ruta de
    renderizado actual. Nuestro componente `ErrorBoundary` maneja este
    redireccionamiento automáticamente por ti.
  - Ejemplo: `throw new RedirectError('/login')`

Para usar, importa desde `blitz` y usa como cualquier Error de JavaScript. Si
eres una persona curiosa, puedes [ver el código fuente de estos](https://github.com/blitz-js/blitz/blob/canary/packages/core/src/errors.ts).

```ts
import { AuthenticationError } from "blitz"

try {
  throw new AuthenticationError()
} catch (error) {
  if (error.name === "AuthenticationError") {
    // Manejar el error adecuadamente, por ejemplo mostrar una pantalla de login
    console.log(error.statusCode)
    console.log(error.message)
  }
}
```

Puedes lanzar estos o cualquier otro error desde cualquier lugar de tu
aplicación, sea en el servidor o en el cliente.

## Capturando y Manejando Errores en el Cliente {#catching-and-handling-errors-on-the-client}

Manejas los errores en el cliente usando [`<ErrorBoundary>`](./error-boundary).

Por defecto, las nuevas aplicaciones de Blitz incluyen un `<ErrorBoundary>` de
mayor nivel y un `FallbackComponent` en `app/pages/_app.tsx`.

Es algo como esto:

```tsx
// app/pages/_app.tsx
import {
  AppProps,
  ErrorBoundary,
  ErrorComponent,
  useQueryErrorResetBoundary,
} from "blitz"
import LoginForm from "app/auth/components/LoginForm"

export default function App({ Component, pageProps }: AppProps) {
  // Esto asegura que el hook useQuery de Blitz automáticamente vuelve a
  // pedir los datos en cualquier ocación que resetees el ErrorBoundary.
  const { reset } = useQueryErrorResetBoundary()

  return (
    <ErrorBoundary FallbackComponent={RootErrorFallback} onReset={reset}>
      <Component {...pageProps} />
    </ErrorBoundary>
  )
}

function RootErrorFallback({ error, resetErrorBoundary }) {
  if (error.name === "AuthenticationError") {
    return <LoginForm onSuccess={resetErrorBoundary} />
  } else if (error.name === "AuthorizationError") {
    return (
      <ErrorComponent
        statusCode={error.statusCode}
        title="Sorry, you are not authorized to access this"
      />
    )
  } else {
    return (
      <ErrorComponent
        statusCode={error.statusCode || 400}
        title={error.message || error.name}
      />
    )
  }
}
```

Esto significa que todos los errores seran capturados al menos al nivel raíz.
Sin embargo, también puedes agregar un `<ErrorBoundary>` en cualquer lugar de tu
aplicación y manejar los errores de una manera más localizada. Para hacer esto,
declara un `useQueryErrorResetBoundary` separado en tu componente y pasalo junto
al _ErrorBoundary_ local. Si un error es capturado por un `<ErrorBoundary>` en
algún lugar dentro del árbol de tu aplicación, no llegará al _ErrorBoundary_ en
la raíz, a menos que se lanze nuevamente.

### Manejando Errores del Servidor en el Cliente {#handling-server-errors-on-the-client}

Una característica increíble de Bliz es que puede lanzar cualquier error
desde una mutación o consulta de Blitz y luego usar un _ErrorBoundary_ en el
_frontend_ para caprutarlo y manejarlo.

Por ejemplo, con el `_app.tsx` de arriba, puedes lanzar un `AuthenticationError`
dentro de la consulta de Blitz y luego una pantalla de _login_ se mostrará
automáticamente en el cliente porque el _ErrorBoundary_ raíz está renderizando
un `<LoginForm>` si `error.name === 'AuthenticationError'`.

### Errores Personalizados {#custom-errors}

Para errores adicionales a los que Blitz provee, se recomienda crear clases de
Errores personalizadas. Entonces puedes agegar propiedades de datos
personalizadas que te ayuden a manejar el error.

Aquí hay un ejemplo de un error personalizado. Es una clase de JavaScript,
entonces puedes ser tan creativo o creativa como quieras.

```ts
import SuperJson from "superjson"

export class UsernameTakenError extends Error {
  name = "UsernameTakenError"
  constructor({ suggestedUserName }) {
    super()
    this.suggestedUserName = suggestedUserName
  }
}
// Registrar con el serializador SuperJson para que se reconstruya en el cliente
SuperJson.registerClass(UsernameTakenError)
SuperJson.allowErrorProps("suggestedUserName")

throw new UsernameTakenError({ suggestedUserName: "second_best" })
```

Nota que **debes registrarlo con SuperJson** como se muestra arriba para que
`instanceof` funcione en el cliente. Y debes decirle a SuperJson acerca de
cualquier propiedad de error especial que quieras que sea serializada. Por
defecto, las popiedades de los errores personalizados son son omitidas por
razones de seguridad.

Luego en el cliente, puedes usar un `FallbackComponent` como arriba, o puedes
manejar el error en el manejador de envío de tu formulario de la siguiente
manera.
```tsx
<Form
  onSubmit={async (values) => {
    try {
      await setUsername(values.username)
    } catch (error) {
      if (error instanceof UsernameTakenError) {
        setSuggestedUsername(error.suggestedUserName)
      }
    }
  }}
/>
```

## Páginas de Error {#error-pages}

Mira la [documentación de Paginas de Error](./error-pages) para aprender más
sobre páginas de error personalizadas y componentes _fallback_ de error.
